# Generated by Django 2.2.3 on 2019-08-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='context',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题'),
        ),
    ]
