# Generated by Django 2.2.3 on 2019-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190824_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/%Y/%m/', verbose_name='展示的图片'),
        ),
    ]
