# Generated by Django 2.2.3 on 2019-07-20 03:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=ckeditor.fields.RichTextField(verbose_name='文章内容'),
        ),
    ]
