# Generated by Django 2.2.3 on 2019-08-13 06:42

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190720_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
    ]
