# Generated by Django 2.2.3 on 2019-08-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190813_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show',
            field=models.BooleanField(default=True, verbose_name='列表显示'),
        ),
    ]
