# Generated by Django 2.2.3 on 2019-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='友链名称')),
                ('url', models.URLField(verbose_name='网站')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='增加时间')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
    ]
